modLoader="javafml" #mandatory
loaderVersion="[28,)" #mandatory (28 is current forge version)
issueTrackerURL="https://github.com/kreezxil/better-with-minecolonies/issues" #optional
[[mods]] #mandatory
modId="betterwithminecolonies" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Better With Minecolonies" #mandatory
updateJSONURL="http://myurl.me/" #optional
displayURL="https://www.curseforge.com/minecraft/mc-mods/better-with-minecolonies" #optional
logoFile="examplemod.png" #optional
credits="Kreezxil" #optional
authors="Donate to my projects at https://patreon.com/kreezxil" #optional

description='''
A mod that fixes a bunch of recipes to make 1.14.4 more enjoyable especially when
used with Minecolonies.

Note: Minecolonies is not a requirement to benefit!

Adds in recipes to get flowers so you don't have to go bonemeal crazy, also you can get grass and path blocks, and dyes from coral.
'''

[[dependencies.betterwithminecolonies]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[28,)" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.betterwithminecolonies]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"
